name: Basic CI Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  basic-check:
    runs-on: ubuntu-latest
    name: Check & Log Repo Info

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install lychee
      run: cargo install lychee

    - name: Check for dead links
      run: lychee . --exclude-path "https://formspree.io/f/xovegebo" --no-progress --exclude https://formspree.io/f/xovegebo
    
    - name: Run accessibility tests
      run: pa11y https://apiarylogic.com

    - name: List files
      run: ls -la
